name: ecommerce1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.0.0
  iconsax: ^0.0.8 
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.5
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/logo_dark.png
    - assets/logos/logo_light.jpg
    - assets/logos/google.png
    - assets/logos/facebook.png
    - assets/images/animation/
    - assets/images/on_boarding_images/
    - assets\images\animation\cutegirl.gif

  fonts:
    - family: interpub 
      fonts:
        - asset: assets/fonts/interitalic.ttf
          style: italic
          weight: 700


